services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: company
      POSTGRES_USER: nihal
      POSTGRES_PASSWORD: nihal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nihal
    ports:
      - "5050:80"
    depends_on:
      - postgres

  company-service:
    image: company-service
    container_name: company-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/company
      SPRING_DATASOURCE_USERNAME: nihal
      SPRING_DATASOURCE_PASSWORD: nihal
    depends_on:
      - postgres

  job-service:
    image: job-service
    container_name: job-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/company
      SPRING_DATASOURCE_USERNAME: nihal
      SPRING_DATASOURCE_PASSWORD: nihal
    depends_on:
      - postgres

  review-service:
    image: review-service
    container_name: review-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/company
      SPRING_DATASOURCE_USERNAME: nihal
      SPRING_DATASOURCE_PASSWORD: nihal
    depends_on:
      - postgres

volumes:
  postgres_data:
