name: CI - Maven, Docker Build & Push (Java 21)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 3. Maven build - API Gateway
      - name: Maven build - API Gateway
        run: |
          cd api-gateway/gateway
          mvn clean package -DskipTests

      # 4. Maven build - Company Service
      - name: Maven build - Company Service
        run: |
          cd company-service/companyms
          mvn clean package -DskipTests

      # 5. Maven build - Job Service
      - name: Maven build - Job Service
        run: |
          cd job-service/jobms
          mvn clean package -DskipTests

      # 6. Maven build - Review Service
      - name: Maven build - Review Service
        run: |
          cd review-service/reviewms
          mvn clean package -DskipTests

      # 7. Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Build & Push API Gateway
      - name: Build & Push API Gateway
        run: |
          docker build -t nihalsingh321/api-gateway:latest ./api-gateway/gateway
          docker push nihalsingh321/api-gateway:latest

      # 9. Build & Push Company Service
      - name: Build & Push Company Service
        run: |
          docker build -t nihalsingh321/company-service:latest ./company-service/companyms
          docker push nihalsingh321/company-service:latest

      # 10. Build & Push Job Service
      - name: Build & Push Job Service
        run: |
          docker build -t nihalsingh321/job-service:latest ./job-service/jobms
          docker push nihalsingh321/job-service:latest

      # 11. Build & Push Review Service
      - name: Build & Push Review Service
        run: |
          docker build -t nihalsingh321/review-service:latest ./review-service/reviewms
          docker push nihalsingh321/review-service:latest
